export interface MedicalSpecialty {
  id: string;
  slug: string;
  nameFa: string;
  nameEn: string;
  nameAr: string;
  icon: string;
  descFa: string;
  descEn: string;
  descAr: string;
}

export const CLINICAL_SPECIALTIES: MedicalSpecialty[] = [
  {
    id: "orthopedics",
    slug: "orthopedics",
    nameFa: "ارتوپدی",
    nameEn: "Orthopedics",
    nameAr: "جراحة العظام",
    icon: "accessibility_new",
    descFa: "جراحی استخوان، مفاصل، ستون فقرات و آسیب‌های ورزشی",
    descEn: "Bone, joint, spine surgery and sports injuries",
    descAr: "جراحة العظام والمفاصل والعمود الفقري والإصابات الرياضية",
  },
  {
    id: "urology",
    slug: "urology",
    nameFa: "ارولوژی",
    nameEn: "Urology",
    nameAr: "مسالك بولية",
    icon: "water_drop",
    descFa: "کلیه، مجاری ادراری، پروستات و ناباروری مردان",
    descEn: "Kidney, urinary tract, prostate, and male fertility",
    descAr: "الكلى والمسالك البولية والبروستاتا وعقم الرجال",
  },
  {
    id: "pediatrics",
    slug: "pediatrics",
    nameFa: "اطفال و کودکان",
    nameEn: "Pediatrics",
    nameAr: "طب الأطفال",
    icon: "child_care",
    descFa: "رشد، واکسیناسیون، تغذیه کودک و بیماری‌های نوزادان",
    descEn: "Growth, immunization, child nutrition, and neonatal care",
    descAr: "النمو والتطعيم وتغذية الأطفال ورعاية حديثي الولادة",
  },
  {
    id: "oncology",
    slug: "oncology",
    nameFa: "انکولوژی",
    nameEn: "Oncology",
    nameAr: "طب الأورام",
    icon: "biotechnology",
    descFa: "تشخیص، شیمی‌درمانی، پرتودرمانی و پایش سرطان",
    descEn: "Diagnosis, chemotherapy, radiotherapy, and cancer monitoring",
    descAr: "تشخيص السرطان والعلاج الكيميائي والإشعاعي",
  },
  {
    id: "dermatology",
    slug: "dermatology",
    nameFa: "پوست و مو",
    nameEn: "Dermatology",
    nameAr: "الجلدية والتناسلية",
    icon: "face",
    descFa: "درمان بیماری‌های پوست، مو، ناخن و لیزر درمانی",
    descEn: "Skin, hair, nail disorders and laser treatments",
    descAr: "علاج أمراض الجلد والشعر والأظافر والعلاج بالليزر",
  },
  {
    id: "ophthalmology",
    slug: "ophthalmology",
    nameFa: "چشم‌پزشکی",
    nameEn: "Ophthalmology",
    nameAr: "طب العيون",
    icon: "visibility",
    descFa: "جراحی چشم، عیوب انکساری، آب مروارید و لیزیک",
    descEn: "Eye surgery, refractive errors, cataracts, and LASIK",
    descAr: "جراحة العيون وعيوب الانكسار وإعتام عدسة العين والليزك",
  },
  {
    id: "internal",
    slug: "internal",
    nameFa: "داخلی",
    nameEn: "Internal Medicine",
    nameAr: "الطب الباطني",
    icon: "vital_signs",
    descFa: "گوارش، ریه، کبد، روماتولوژی و دیابت",
    descEn: "Gastroenterology, pulmonology, liver, rheumatology, and diabetes",
    descAr: "أمراض الجهاز الهضمي والرئتين والكبد والروماتيزم والسكري",
  },
  {
    id: "dentistry",
    slug: "dentistry",
    nameFa: "دندانپزشکی",
    nameEn: "Dentistry",
    nameAr: "طب الأسنان",
    icon: "dentistry",
    descFa: "ایمپلنت، عصب‌کشی، ارتودنسی و ترمیم زیبایی",
    descEn: "Implants, root canal, orthodontics, and cosmetic restoration",
    descAr: "زراعة الأسنان وعلاج الجذور والتقويم والترميم التجميلي",
  },
  {
    id: "psychiatry",
    slug: "psychiatry",
    nameFa: "روانپزشکی",
    nameEn: "Psychiatry",
    nameAr: "الطب النفسي",
    icon: "psychology",
    descFa: "درمان اضطراب، افسردگی، وسواس و روان‌درمانی",
    descEn: "Anxiety, depression, OCD treatment and psychotherapy",
    descAr: "علاج القلق والاكتئاب والوسواس القهري والعلاج النفسي",
  },
  {
    id: "gynecology",
    slug: "gynecology",
    nameFa: "زنان و زایمان",
    nameEn: "Gynecology & Obstetrics",
    nameAr: "النساء والتوليد",
    icon: "pregnant_woman",
    descFa: "مراقبت‌های بارداری، زایمان، نازایی و جراحی‌های زنان",
    descEn: "Prenatal care, childbirth, infertility, and gynecological surgery",
    descAr: "رعاية الحمل والولادة والعقم والجراحة النسائية",
  },
  {
    id: "traditional",
    slug: "traditional",
    nameFa: "طب سنتی و ایرانی",
    nameEn: "Traditional Persian Medicine",
    nameAr: "الطب التقليدي الإيراني",
    icon: "eco",
    descFa: "اصلاح مزاج، تدابیر تغذیه‌ای، گیاه‌درمانی و حجامت طبی",
    descEn: "Temperament balance, dietary regimens, phytotherapy, and cupping",
    descAr: "تعديل المزاج والنظام الغذائي والعلاج بالأعشاب والحجامة الطبية",
  },
  {
    id: "cardiology",
    slug: "cardiology",
    nameFa: "قلب و عروق",
    nameEn: "Cardiology",
    nameAr: "أمراض القلب والأوعية",
    icon: "cardiology",
    descFa: "اکوکاردیوگرافی، نوار قلب، فشار خون و آنژیوگرافی",
    descEn: "Echocardiography, ECG, hypertension, and angiography",
    descAr: "تخطيط صدى القلب وتخطيط القلب الكهربائي وضغط الدم",
  },
  {
    id: "neurology",
    slug: "neurology",
    nameFa: "مغز و اعصاب",
    nameEn: "Neurology",
    nameAr: "أمراض المخ والأعصاب",
    icon: "neurology",
    descFa: "میگرن، صرع، ام‌اس، سکته مغزی و دیسک کمر",
    descEn: "Migraine, epilepsy, MS, stroke, and disc herniation",
    descAr: "الصداع النصفي والصرع والتصلب المتعدد والسكتة الدماغية",
  },
];
