import {
  Accessibility,
  Activity,
  AlarmClock,
  Ambulance,
  Apple,
  Armchair,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Atom,
  AudioWaveform,
  Award,
  Baby,
  Badge,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Bandage,
  Banknote,
  Bell,
  BellOff,
  Bone,
  BookOpen,
  Brain,
  BrainCircuit,
  Briefcase,
  BriefcaseMedical,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarX,
  Car,
  ChartLine,
  ChartPie,
  Check,
  CheckCheck,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheckBig,
  CircleHelp,
  CirclePlay,
  CirclePlus,
  CircleUserRound,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudUpload,
  Coffee,
  CookingPot,
  Copy,
  CreditCard,
  Croissant,
  Dna,
  Download,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Egg,
  Eye,
  FileDown,
  FilePenLine,
  FilePlus,
  FileQuestion,
  FileText,
  FileWarning,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  FolderOpen,
  Footprints,
  Gauge,
  Gavel,
  Globe,
  Grab,
  GraduationCap,
  Hand,
  HandPlatter,
  Handshake,
  Headset,
  HeartHandshake,
  HeartPulse,
  Hospital,
  Hourglass,
  House,
  HousePlus,
  Inbox,
  Info,
  Landmark,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  ListFilter,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Mars,
  Menu,
  MessageCircle,
  MessagesSquare,
  Mic,
  Moon,
  Navigation,
  Network,
  Newspaper,
  NotebookPen,
  OctagonAlert,
  Paperclip,
  PenLine,
  Pencil,
  PersonStanding,
  Phone,
  PhoneCall,
  PhoneIncoming,
  Pill,
  Pin,
  Play,
  Plus,
  Printer,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Rocket,
  Ruler,
  Salad,
  Sandwich,
  Save,
  Scale,
  Scan,
  ScanFace,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShieldPlus,
  Siren,
  Smartphone,
  Smile,
  SmilePlus,
  Soup,
  Sparkles,
  Square,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Tag,
  Terminal,
  TestTube,
  Ticket,
  Timer,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  User,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  Utensils,
  UtensilsCrossed,
  Venus,
  Video,
  VideoOff,
  Wallet,
  Weight,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type { LucideIcon };

// Canonical Material Symbols (ligature) name -> lucide-react component.
// Covers every distinct icon name inventoried across src (static
// name="...", dynamic name={...} literals, data-array icon:"..." strings,
// and message-catalog avatarIcon values) so later page migrations can
// resolve through this table.
export const iconByName: Record<string, LucideIcon> = {
  accessibility_new: Accessibility,
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  account_circle: CircleUserRound,
  add: Plus,
  add_circle: CirclePlus,
  admin_panel_settings: ShieldCheck,
  airline_seat_recline_normal: Armchair,
  alarm: AlarmClock,
  ambulance: Ambulance,
  analytics: ChartLine,
  apartment: Building2,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_left: ArrowLeft,
  arrow_upward: ArrowUp,
  article: Newspaper,
  assignment: ClipboardList,
  attach_file: Paperclip,
  badge: Badge,
  bakery_dining: Croissant,
  balance: Salad,
  biotech: Dna,
  biotechnology: FlaskConical,
  bloodtype: Droplets,
  bolt: Zap,
  business: Briefcase,
  calculate: Calculator,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  call: Phone,
  cardiology: HeartPulse,
  category: LayoutGrid,
  chat: MessageCircle,
  check: Check,
  check_circle: CircleCheckBig,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  child_care: Baby,
  child_friendly: Smile,
  clinical_notes: NotebookPen,
  close: X,
  cloud_upload: CloudUpload,
  confirmation_number: Ticket,
  content_copy: Copy,
  corporate_fare: Building2,
  credit_card_off: CreditCard,
  crop_square: Square,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  dentistry: SmilePlus,
  description: FileText,
  deskphone: PhoneIncoming,
  dinner_dining: HandPlatter,
  directions_car: Car,
  directions_walk: Footprints,
  domain: Building,
  done_all: CheckCheck,
  download: Download,
  ecg: AudioWaveform,
  eco: Leaf,
  edit: Pencil,
  edit_note: FilePenLine,
  egg: Egg,
  elderly: PersonStanding,
  emergency: Siren,
  error: CircleAlert,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  event_note: CalendarClock,
  expand_more: ChevronDown,
  face: ScanFace,
  fact_check: ClipboardCheck,
  female: Venus,
  filter_list: ListFilter,
  fitness_center: Dumbbell,
  flag: Flag,
  flatware: UtensilsCrossed,
  folder_shared: FolderOpen,
  footprint: Footprints,
  forum: MessagesSquare,
  gavel: Gavel,
  group: Users,
  hand_gesture: Grab,
  handshake: Handshake,
  healing: Bandage,
  health_and_safety: ShieldPlus,
  health_metrics: Gauge,
  hearing: Ear,
  help: CircleHelp,
  help_center: LifeBuoy,
  home: House,
  home_health: HousePlus,
  hourglass_top: Hourglass,
  hub: Network,
  inbox: Inbox,
  info: Info,
  lab_profile: TestTube,
  label: Tag,
  language: Languages,
  light_mode: Sun,
  lightbulb: Lightbulb,
  local_cafe: Coffee,
  local_fire_department: Flame,
  local_hospital: Hospital,
  location_on: MapPin,
  lock: Lock,
  logout: LogOut,
  lunch_dining: Sandwich,
  mail: Mail,
  male: Mars,
  man: User,
  medical_services: BriefcaseMedical,
  medication: Pill,
  menu: Menu,
  menu_book: BookOpen,
  monitor_weight: Scale,
  near_me: Navigation,
  neurology: Brain,
  no_food: Ban,
  notifications: Bell,
  notifications_none: BellOff,
  nutrition: Apple,
  pan_tool: Hand,
  payment: CreditCard,
  payments: Banknote,
  person: User,
  person_add: UserPlus,
  phone_in_talk: PhoneCall,
  phone_iphone: Smartphone,
  picture_as_pdf: FileDown,
  pie_chart: ChartPie,
  pin: Pin,
  play_arrow: Play,
  play_circle: CirclePlay,
  post_add: FilePlus,
  pregnant_woman: HeartHandshake,
  price_check: BadgeDollarSign,
  print: Printer,
  psychology: BrainCircuit,
  quiz: FileQuestion,
  radiology: Scan,
  rate_review: PenLine,
  receipt_long: ReceiptText,
  record_voice_over: Mic,
  replay: RotateCcw,
  report: FileWarning,
  report_problem: OctagonAlert,
  respiratory_rate: Wind,
  restaurant: Utensils,
  restaurant_menu: ChefHat,
  save: Save,
  scale: Weight,
  schedule: Clock,
  school: GraduationCap,
  science: Atom,
  search: Search,
  search_off: SearchX,
  security: Fingerprint,
  send: Send,
  settings: Settings,
  shield: Shield,
  skeleton: Bone,
  sort: ArrowUpDown,
  soup_kitchen: Soup,
  spa: Flower2,
  spoon: CookingPot,
  sports_mma: Trophy,
  sprint: Rocket,
  star: Star,
  stethoscope: Stethoscope,
  straighten: Ruler,
  support_agent: Headset,
  sync: RefreshCw,
  sync_alt: ArrowLeftRight,
  terminal: Terminal,
  timer: Timer,
  tips_and_updates: Sparkles,
  translate: Globe,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  vaccines: Syringe,
  verified: BadgeCheck,
  verified_user: UserCheck,
  videocam: Video,
  videocam_off: VideoOff,
  visibility: Eye,
  vital_signs: Activity,
  warning: TriangleAlert,
  water_drop: Droplet,
  wb_sunny: Sunrise,
  wb_twilight: Sunset,
  woman: UserRound,
  workspace_premium: Award,
};

// Unknown names at runtime fall back to CircleHelp so migrated dynamic
// lookups (resolveIcon(var)) never render a broken glyph.
export function resolveIcon(name: string): LucideIcon {
  return iconByName[name] ?? CircleHelp;
}
