import {
  Accessibility,
  Activity,
  AlarmClock,
  Apple,
  ArrowLeft,
  ArrowRight,
  Baby,
  Bell,
  Bone,
  BookOpen,
  Brain,
  BrainCircuit,
  BriefcaseMedical,
  Calendar,
  CalendarDays,
  CircleAlert,
  CircleHelp,
  Dna,
  Droplet,
  Droplets,
  Dumbbell,
  Eye,
  FlaskConical,
  Flower2,
  Headset,
  HeartHandshake,
  HeartPulse,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  MapPin,
  Network,
  Newspaper,
  ScanFace,
  Settings,
  Shield,
  ShieldPlus,
  SmilePlus,
  Stethoscope,
  User,
  Utensils,
  Wind,
  Atom,
  type LucideIcon,
} from "lucide-react";

export type { LucideIcon };

// Canonical Material Symbols (ligature) name -> lucide-react component.
// Trimmed to names actually passed to resolveIcon across src (specialty,
// admin-nav, notification, topic, search, and empty-state lookups).
// Unknown names fall back to CircleHelp so dynamic lookups never break.
export const iconByName: Record<string, LucideIcon> = {
  accessibility_new: Accessibility,
  alarm: AlarmClock,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  article: Newspaper,
  biotech: Dna,
  biotechnology: FlaskConical,
  bloodtype: Droplets,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  cardiology: HeartPulse,
  category: LayoutGrid,
  child_care: Baby,
  dashboard: LayoutDashboard,
  dentistry: SmilePlus,
  eco: Leaf,
  error: CircleAlert,
  face: ScanFace,
  fitness_center: Dumbbell,
  health_and_safety: ShieldPlus,
  hub: Network,
  inbox: Inbox,
  location_on: MapPin,
  medical_services: BriefcaseMedical,
  menu_book: BookOpen,
  neurology: Brain,
  notifications: Bell,
  nutrition: Apple,
  person: User,
  pregnant_woman: HeartHandshake,
  psychology: BrainCircuit,
  respiratory_rate: Wind,
  restaurant: Utensils,
  science: Atom,
  settings: Settings,
  shield: Shield,
  skeleton: Bone,
  spa: Flower2,
  stethoscope: Stethoscope,
  support_agent: Headset,
  visibility: Eye,
  vital_signs: Activity,
  water_drop: Droplet,
};

// Unknown names at runtime fall back to CircleHelp so migrated dynamic
// lookups (resolveIcon(var)) never render a broken glyph.
export function resolveIcon(name: string): LucideIcon {
  return iconByName[name] ?? CircleHelp;
}
